version: '3.8'

services:
  todo-app:
    build: .
    container_name: todo-app
    restart: always
    ports:
      - "80:3000"
    environment:
      MYSQL_HOST: 192.168.23.1
      MYSQL_USER: todo
      MYSQL_PASSWORD: todopass
      MYSQL_DATABASE: todo